AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  finance-app-fn

  Sample SAM Template for finance-app-fn
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ProcessRecurringTransactionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: processRecurringTransactions/
      Handler: app.lambdaHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Events:
        ProcessRecurringTransactionsSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(* * * * ? *)

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProcessRecurringTransactionsFunction:
    Description: "Process Recurring Transactions Lambda Function ARN"
    Value: !GetAtt ProcessRecurringTransactionsFunction.Arn
  ProcessRecurringTransactionsFunctionIamRole:
    Description: "Implicit IAM Role created for Process Recurring Transactions function"
    Value: !GetAtt ProcessRecurringTransactionsFunctionRole.Arn
