"use client";

import { Card } from "@/components/ui/Card";

export default function HelpPage() {
  return (
    <div className="p-6 lg:p-8 flex flex-col gap-6 min-h-screen">
      <div>
        <h1 className="font-display font-black text-2xl text-white">Help</h1>
        <p className="text-white/40 font-body text-sm mt-1">
          How Ledger works, including budgets, split-aware transactions, debt tracking, recurring schedules, and reports.
        </p>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
        <Card className="p-5">
          <h2 className="font-display font-bold text-white text-lg mb-2">Getting Started</h2>
          <ul className="text-sm text-white/70 font-body leading-6 space-y-1">
            <li>1. Sign in with Firebase email magic link authentication.</li>
            <li>2. Create a budget from the sidebar budget selector.</li>
            <li>3. Add people to the selected budget in the People page.</li>
            <li>4. Add transactions (income/expense) tied to a person and category.</li>
          </ul>
        </Card>

        <Card className="p-5">
          <h2 className="font-display font-bold text-white text-lg mb-2">Budgets And People</h2>
          <ul className="text-sm text-white/70 font-body leading-6 space-y-1">
            <li>Budgets separate data contexts (transactions, people, summaries).</li>
            <li>Active budget in the sidebar controls what all pages show.</li>
            <li>People are budget-scoped and used for contribution reporting.</li>
            <li>Each person has a color used across charts and transaction listings.</li>
            <li>People page includes a Debt Tracker for who owes who.</li>
            <li>People page includes Cash Assets with editable starting cash per person.</li>
          </ul>
        </Card>

        <Card className="p-5">
          <h2 className="font-display font-bold text-white text-lg mb-2">Debt Tracker</h2>
          <ul className="text-sm text-white/70 font-body leading-6 space-y-1">
            <li>Set who owes and who is owed for the selected budget.</li>
            <li>Set starting debt to include debt from before app usage.</li>
            <li>Total owed auto-updates from completed split-aware expense transactions.</li>
            <li>If creditor paid debtor share, debt goes up; if debtor paid creditor share, debt goes down.</li>
            <li>Use Record repayment to reduce the debt baseline after paybacks.</li>
            <li>Contribution gap shows whether one person is behind or ahead on split-aware expenses.</li>
          </ul>
        </Card>

        <Card className="p-5">
          <h2 className="font-display font-bold text-white text-lg mb-2">Transactions Page</h2>
          <ul className="text-sm text-white/70 font-body leading-6 space-y-1">
            <li>Search filters by description/category text.</li>
            <li>Type and category dropdowns narrow the list instantly.</li>
            <li>Add/Edit transaction includes Paid by person and Split type fields.</li>
            <li>Columns menu lets you show/hide table columns.</li>
            <li>Select rows with checkboxes and use Delete for bulk removal.</li>
            <li>Use Import CSV and Export for bulk data operations.</li>
            <li>Refresh reloads data from Firestore for current budget.</li>
          </ul>
        </Card>

        <Card className="p-5">
          <h2 className="font-display font-bold text-white text-lg mb-2">Transaction View Modes</h2>
          <ul className="text-sm text-white/70 font-body leading-6 space-y-1">
            <li><span className="text-white">Completed</span>: shows transactions up to now/today.</li>
            <li><span className="text-white">Upcoming</span>: shows future transactions only.</li>
            <li><span className="text-white">All</span>: shows completed and upcoming together.</li>
            <li>Recurring templates are hidden from Upcoming to avoid duplicates.</li>
            <li>For each recurring template, only one next upcoming occurrence is shown.</li>
            <li>If no future occurrence exists yet, a synthetic next row is generated and marked <span className="text-volt">Next scheduled</span>.</li>
          </ul>
        </Card>

        <Card className="p-5">
          <h2 className="font-display font-bold text-white text-lg mb-2">Recurring Transactions</h2>
          <ul className="text-sm text-white/70 font-body leading-6 space-y-1">
            <li>Create a recurring transaction in Add/Edit with frequency and interval.</li>
            <li>Recurrence supports minute, hour, daily, weekly, monthly, yearly.</li>
            <li>Recurring templates carry recurrence rules and group identifiers.</li>
            <li>Occurrences are generated by the scheduled recurring processor.</li>
            <li>Edit modal supports scope options: this, this and future, or all in series.</li>
          </ul>
        </Card>

        <Card className="p-5">
          <h2 className="font-display font-bold text-white text-lg mb-2">Dashboard And Charts</h2>
          <ul className="text-sm text-white/70 font-body leading-6 space-y-1">
            <li>Period tabs switch weekly, fortnightly, monthly, yearly summaries.</li>
            <li>Stat cards summarize income, expenses, and net values.</li>
            <li>Charts include monthly trends, category breakdown, and person contributions.</li>
            <li>All metrics are computed from transactions in the active budget.</li>
          </ul>
        </Card>
      </div>

      <Card className="p-5">
        <h2 className="font-display font-bold text-white text-lg mb-2">Data And Security</h2>
        <ul className="text-sm text-white/70 font-body leading-6 space-y-1">
          <li>Authentication is handled by Firebase Auth (email link/passwordless).</li>
          <li>Firestore stores budgets, people, and transactions with per-user rules.</li>
          <li>CSV import expects valid transaction fields and category/type values.</li>
          <li>Exports include transaction data for offline analysis or migration.</li>
        </ul>
      </Card>
    </div>
  );
}
